name: CI

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
    

 
jobs:
  build:
    environment: "${{ inputs.environment }}"
    runs-on: ubuntu-latest

   
    steps:
      
        - uses: actions/checkout@v3
        
        - run: echo "Die Enviroment ist ${{ inputs.enviroment }}"
        - run: echo "Der wer der Enviroment-Varibale Discription ${{ vars.Discription }}"
        - run: echo "Mein Bentuzer-Secret ist ${{ secrets.MONGODB_USERNAME }}"
      
